apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: test
spec:
  restartPolicy: Never
  containers:
  - image: nginx:1.14.2
    name: c1
    command: 
    - /bin/bash
    imagePullPolicy: Always
    # resources:
    #   requests:
    #     cpu: "1"
    #     memory: "500Mi"
    #   limits:
    #     cpu: "1"
    #     memory: "500Mi"
  imagePullSecrets:
    - name: regcred
