DcssDividePolicy: random
DcssNeibor: 4
DcssNeiborRandomP: 0.5
DockerImageRepo: registry.cn-hangzhou.aliyuncs.com/lin2631/simlet:latest
FPS: 10000
GoProcs: 3
K8SConfig: /home/lin/.kube/config
K8STemplatePath: ./simctl/template
NetLatency: 1
NodeCpu: 1000
NodeMemory: 1000
NodeNum: 20
SimulateDuration: 40000
StateUpdatePeriod: 100
TaskCpu: 300
TaskLifeTime: 330
TaskMemory: 300
TaskMode: onePeak
TaskNumFactor: 6
TraceFile: ./trace/tasks_stream.log
