NodeNum:        1000    # how many large the cluster
NetLatency:     5          # the average network latency, unit: milisecond 
NodeCpu:        1000         # the node cpu capacity
NodeMemory:     1000         # the node memory capacity
TaskNumFactor:  6        # task/persecond = TaskNumFactor * NodeNum 
TaskCpu:        300          # the average task cpu request
TaskMemory:     300          # the average task memory request
TaskLifeTime:   330        # the average task lifeTime  , unit : milisecond


#only in center and shareState 
SchedulerPerformance: 4000  # how many time Scheduler execute scheduling algorithm in 1s

# only in dcss mode
DcssNeibor:    16          #how many neibor of a node
DcssNeiborRandomP:      0.99         #how many random neibor of a node
DcssDividePolicy     : "always"  #

# only in share state cluster
StateUpdatePeriod:   300   # the period of scheduler get the newest cluster state, unit : milisecond
