NodeNum:        1000
NetLatency:     100
DcssNeibor:     8
NodeCpu:        10
NodeMemory:     10
TaskNumFactor:  8.0
TaskCpu:        3
TaskMemory:     3
TaskLifeTime:   333
SchedulerPerformance: 11.0
