apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcss-test-etcd
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd1
        image: registry.cn-hangzhou.aliyuncs.com/cyx123/etcd:v3.2.8
        command: ["/bin/sh"]
        args: [
          "-c",
          "
            etcd --name s1 --listen-client-urls http://0.0.0.0:2379  --advertise-client-urls http://0.0.0.0:2379
          "
        ]
        ports:
        - containerPort: 2379
        - containerPort: 2380
