NodeNum:        100     # how many large the cluster
NetLatency:     5          # the average network latency, unit: milisecond 
NodeCpu:        10         # the node cpu capacity
NodeMemory:     10         # the node memory capacity
TaskNumFactor:  6        # task/persecond = TaskNumFactor * NodeNum 
TaskCpu:        3          # the average task cpu request
TaskMemory:     3          # the average task memory request
TaskLifeTime:   333        # the average task lifeTime  , unit : milisecond


#only in center and shareState 
SchedulerPerformance: 4000  # how many time Scheduler execute scheduling algorithm in 1s

# only in dcss mode
DcssNeibor:     8          #how many neibor of a node
DcssNeiborRandomP:      0.5         #how many random neibor of a node
DcssDividePolicy     : "always"  #

# only in share state cluster
StateUpdatePeriod:   300   # the period of scheduler get the newest cluster state, unit : milisecond
