DcssDividePolicy: always
DcssNeibor: 12
DcssNeiborRandomP: 1.0
NetLatency: 5
NodeCpu: 10
NodeMemory: 10
NodeNum: 4000
SchedulerPerformance: 40000
StateUpdatePeriod: 100
TaskCpu: 3
TaskLifeTime: 333
TaskMemory: 3
TaskNumFactor: 6.4
