DcssDividePolicy: always
DcssNeibor: 8
DcssNeiborRandomP: 1.0
NetLatency: 5
NodeCpu: 10
NodeMemory: 10
NodeNum: 4000
SchedulerPerformance: 4000
StateUpdatePeriod: 300
TaskCpu: 3
TaskLifeTime: 333
TaskMemory: 3
TaskNumFactor: 6
